### ISSUE TITLE
It's June 3rd...

### ISSUE THREAD

**Issue by bl-ue** [chunky-milk/chunky-milk#1]
Hey there @chunky-milk!  It's June 3rd today — have you changed your username yet?

(Or did you mean June 3rd of 2022? 😄)

**Comment by chunky-milk** [comment]
Hahaha... thanks for reminding me. I will extend the date 😄

**Comment by bl-ue** [comment]
By the way, GitHub will automatically redirect all links that contain your old username to the same link only with your new username, _unless_ someone takes your old username (in which case the links will be 404s).

**Comment by chunky-milk** [comment]
> By the way, GitHub will automatically redirect all links that contain your old username to the same link only with your new username, _unless_ someone takes your old username (in which case the links will be 404s).

I didn't know that! Thanks for the info
